apiVersion: camel.apache.org/v1
kind: IntegrationPlatform
metadata:
  name: camel-k
  namespace: camel-k
spec:
  build:
    registry:
      address: docker.io
      organization: lmhinnel
      insecure: false
      secret: registry
